### ISSUE TITLE
AP Sudoku weird interactions

### ISSUE THREAD

**Issue by G4M3RL1F3** [LittleCube-hax/MMRecompRando#26]
When attempting to connect to a MM Recomp slot through AP Sudoku, it constantly disconnects and reconnects until the window in manually closed. Connecting to any other slot in the same room that is not MM Recomp works just fine. Additionally, based on tests and observations, when a specific location in MM Recomp has been checked, connecting to that slot in AP Sudoku sends another check from a location that hasn't been checked previously.

After encountering this issue for the first time, I decided to spend the time to check most locations to see if this issue could be caused by others. After checking a location, I opened AP Sudoku to see if another random location would send. Below is a list of my findings. In each bullet point, the first location is the one I checked. The second one is the one that was sent by AP Sudoku after attempting to connect.
- `Deku Palace Bean Grotto Chest` → `Termina Peahat Grotto Chest`
- `Milk Road Gorman Ranch Race` → `Laundry Pool Curiosity Shop Salesman #1`
- `Moon's Tear Trade` → `Southern Swamp Deku Trade`
- `Road to Ikana Stone Soldier` → `Laundry Pool Guru-Guru`
- `Termina Tall Grass Chest` → `Termina Underwater Chest`
- `Swamphouse First Room Crawling Right Column Token` → `Swamphouse Pottery Room Left Large Pot Token`
- `Swamphouse First Room Left Bugpatch Token` → `Swamphouse First Room Crawling In Water Token`
- `Swamphouse Pottery Room Small Pot Token` → `Swamphouse Golden Room Crawling Right Column Token`
- `Swamphouse Pottery Room Beehive #1 Token` → `Swamphouse Tree Room Tree #2 Token`
- `Woodfall Temple Entrance Freestanding SF` → `Woodfall Temple Final Room Left Upper Platform SF`
- `Woodfall Temple Gagwab Chest` → `Woodfall Temple Dragonfly Chest`

These were found in one seed. `Termina Tall Grass Chest` → `Termina Underwater Chest` is the one that made me look into it. In a test seed, I avoided `Termina Tall Grass Chest` to see if any other location would send the latter. None other made it send. Near the end of the seed, I checked `Termina Underwater Chest` first to see if the reverse order would do the same, but it didn't.

Notice how the Swamphouse locations were affecting other locations also in Swamphouse. Same for Woodfall Temple. There's also the scrub trades, where the Clock Town one made the Swamp one send. Perhaps this is a lead?

I also thought that maybe it's an item that could cause this, but in a test seed, I checked `Termina Tall Grass Chest`, which gave me Pendant of Memories. Then, AP Sudoku made `Termina Underwater Chest` send. In the following test seed, I had Pendant early on, but haven't checked `Termina Tall Grass Chest` yet. `Termina Underwater Chest` was never sent despite having Pendant.

It might be worth mentioning that every time AP Sudoku attempted to connect, it was sending the following errors:
```
'No location 14767077353062xxx for player 1'
Traceback (most recent call last):
  File "/Projects/Archipelago/MultiServer.py", line 785, in server
    await process_client_cmd(ctx, client, msg)
  File "/Projects/Archipelago/MultiServer.py", line 1804, in process_client_cmd
    target_item, target_player, flags = ctx.locations[client.slot][location]
  File "_speedups.pyx", line 350, in _speedups.PlayerLocationProxy.__getitem__
    raise KeyError(f"No location {key} for player {self._player}")
KeyError: 'No location 14767077353062xxx for player 1'
```
Where you see `xxx` in the first and last lines, numbers were sometimes changing throughout the run between 436, 468, 484, 512, and 528, if that's any relevant. Although, the `__getitem__` part in the 3rd last row catches my eye... To my knowledge, AP Sudoku never sends checks of its associated slot. It only generates hints.

I'm willing to do more of those test seeds to see if there are more of those "locations sent by AP Sudoku". If you need me to do anything specific or to send more details, feel free to ask!

**Comment by LittleCube-hax** [comment]
Ah, **that's** what I forgot to do. 🫠

This has already been fixed, I just didn't release 🥴 I'll do that now.

For the record, it's because the APWorld had its addresses set too high, so any AP framework that relies on the integers being "safe" (Archipelago.js for one) will jump up integers like you saw.

**Comment by LittleCube-hax** [comment]
Released, let me know if it's still broken.
